/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugasakhirpbo;

/**
 *
 * @author Yafi, Alfito, dan Haydar.
 */
public class BangunDatar1 extends javax.swing.JFrame {

    /**
     * Creates new form BangunDatar
     */
    public BangunDatar1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        desktopPaneControl = new javax.swing.JDesktopPane();
        button1 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        desktopPaneControl1 = new javax.swing.JDesktopPane();
        button5 = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        desktopPaneControl2 = new javax.swing.JDesktopPane();
        button8 = new javax.swing.JButton();
        button10 = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        desktopPaneControl3 = new javax.swing.JDesktopPane();
        btnCash = new javax.swing.JButton();
        btnGopay = new javax.swing.JButton();
        btnShope = new javax.swing.JButton();
        btnDebit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jButton1.setText("Persegi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        desktopPaneControl.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout desktopPaneControlLayout = new javax.swing.GroupLayout(desktopPaneControl);
        desktopPaneControl.setLayout(desktopPaneControlLayout);
        desktopPaneControlLayout.setHorizontalGroup(
            desktopPaneControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );
        desktopPaneControlLayout.setVerticalGroup(
            desktopPaneControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(desktopPaneControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 6, -1, 400));

        button1.setText("Persegi");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 104, 175, 50));

        button3.setText("Lingkaran");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        jPanel1.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 216, 175, 50));

        button4.setText("Segitiga");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        jPanel1.add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 272, 175, 50));

        button2.setText("Persegi Panjang");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        jPanel1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 175, 50));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bangun Datar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 175, 80));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background5.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 400));

        jTabbedPane1.addTab("Bangun Datar", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        desktopPaneControl1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout desktopPaneControl1Layout = new javax.swing.GroupLayout(desktopPaneControl1);
        desktopPaneControl1.setLayout(desktopPaneControl1Layout);
        desktopPaneControl1Layout.setHorizontalGroup(
            desktopPaneControl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );
        desktopPaneControl1Layout.setVerticalGroup(
            desktopPaneControl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(desktopPaneControl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 6, -1, 400));

        button5.setText("Bola");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        jPanel2.add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 104, 175, 50));

        button7.setText("Kubus");
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });
        jPanel2.add(button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 216, 175, 50));

        button6.setText("Kerucut");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        jPanel2.add(button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 175, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Bangun Ruang 1");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 6, 175, 80));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background1.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 400));

        jTabbedPane1.addTab("Bangun Ruang 1", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        desktopPaneControl2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout desktopPaneControl2Layout = new javax.swing.GroupLayout(desktopPaneControl2);
        desktopPaneControl2.setLayout(desktopPaneControl2Layout);
        desktopPaneControl2Layout.setHorizontalGroup(
            desktopPaneControl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );
        desktopPaneControl2Layout.setVerticalGroup(
            desktopPaneControl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.add(desktopPaneControl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 6, -1, 400));

        button8.setText("Balok");
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });
        jPanel3.add(button8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 104, 175, 50));

        button10.setText("Tabung");
        button10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button10ActionPerformed(evt);
            }
        });
        jPanel3.add(button10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 216, 175, 50));

        button9.setText("Piramida");
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });
        jPanel3.add(button9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 175, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Bangun Ruang 2");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 6, 175, 80));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background5.png"))); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 400));

        jTabbedPane1.addTab("Bangun Ruang 2", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        desktopPaneControl3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout desktopPaneControl3Layout = new javax.swing.GroupLayout(desktopPaneControl3);
        desktopPaneControl3.setLayout(desktopPaneControl3Layout);
        desktopPaneControl3Layout.setHorizontalGroup(
            desktopPaneControl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );
        desktopPaneControl3Layout.setVerticalGroup(
            desktopPaneControl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.add(desktopPaneControl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 6, -1, 400));

        btnCash.setText("Cash");
        btnCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashActionPerformed(evt);
            }
        });
        jPanel4.add(btnCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 104, 175, 50));

        btnGopay.setText("Gopay");
        btnGopay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGopayActionPerformed(evt);
            }
        });
        jPanel4.add(btnGopay, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 216, 175, 50));

        btnShope.setText("Shoopepay");
        btnShope.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShopeActionPerformed(evt);
            }
        });
        jPanel4.add(btnShope, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 272, 175, 50));

        btnDebit.setText("Debit");
        btnDebit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDebitActionPerformed(evt);
            }
        });
        jPanel4.add(btnDebit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 175, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Pembayaran");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 6, 175, 80));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background1.png"))); // NOI18N
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 400));

        jTabbedPane1.addTab("Pembayaran", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        desktopPaneControl.removeAll();
        Persegi p = new Persegi();
        desktopPaneControl.add(p).setVisible(true);
    }//GEN-LAST:event_button1ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        desktopPaneControl.removeAll();
        Lingkaran l = new Lingkaran();
        desktopPaneControl.add(l).setVisible(true);
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        desktopPaneControl.removeAll();
        Segitiga s = new Segitiga();
        desktopPaneControl.add(s).setVisible(true);
    }//GEN-LAST:event_button4ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        desktopPaneControl.removeAll();
        PersegiPanjang pp = new PersegiPanjang();
        desktopPaneControl.add(pp).setVisible(true);
    }//GEN-LAST:event_button2ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        desktopPaneControl1.removeAll();
        Bola b = new Bola();
        desktopPaneControl1.add(b).setVisible(true);
    }//GEN-LAST:event_button5ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        desktopPaneControl1.removeAll();
        Kubus k = new Kubus();
        desktopPaneControl1.add(k).setVisible(true);
    }//GEN-LAST:event_button7ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        desktopPaneControl1.removeAll();
        Kerucut kc = new Kerucut();
        desktopPaneControl1.add(kc).setVisible(true);
    }//GEN-LAST:event_button6ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        desktopPaneControl2.removeAll();
        Balok bk = new Balok();
        desktopPaneControl2.add(bk).setVisible(true);
    }//GEN-LAST:event_button8ActionPerformed

    private void button10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button10ActionPerformed
        desktopPaneControl2.removeAll();
        Tabung t = new Tabung();
        desktopPaneControl2.add(t).setVisible(true);
    }//GEN-LAST:event_button10ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        desktopPaneControl2.removeAll();
        Piramida pm = new Piramida();
        desktopPaneControl2.add(pm).setVisible(true);
    }//GEN-LAST:event_button9ActionPerformed

    private void btnCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashActionPerformed
        desktopPaneControl3.removeAll();
        Cash c = new Cash();
        desktopPaneControl3.add(c).setVisible(true);
    }//GEN-LAST:event_btnCashActionPerformed

    private void btnGopayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGopayActionPerformed
        desktopPaneControl3.removeAll();
        Gopay g = new Gopay();
        desktopPaneControl3.add(g).setVisible(true);
    }//GEN-LAST:event_btnGopayActionPerformed

    private void btnShopeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShopeActionPerformed
        desktopPaneControl3.removeAll();
        Shopee s = new Shopee();
        desktopPaneControl3.add(s).setVisible(true);
    }//GEN-LAST:event_btnShopeActionPerformed

    private void btnDebitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDebitActionPerformed
        desktopPaneControl3.removeAll();
        Debit d = new Debit();
        desktopPaneControl3.add(d).setVisible(true);
    }//GEN-LAST:event_btnDebitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BangunDatar1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BangunDatar1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BangunDatar1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BangunDatar1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BangunDatar1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCash;
    private javax.swing.JButton btnDebit;
    private javax.swing.JButton btnGopay;
    private javax.swing.JButton btnShope;
    private javax.swing.JButton button1;
    private javax.swing.JButton button10;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JDesktopPane desktopPaneControl;
    private javax.swing.JDesktopPane desktopPaneControl1;
    private javax.swing.JDesktopPane desktopPaneControl2;
    private javax.swing.JDesktopPane desktopPaneControl3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
