/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tugasakhirpbo;

/**
 *
 * @author Yafi, Alfito, dan Haydar.
 */
public class Bola extends javax.swing.JInternalFrame {
double jari, luas, volume;

    public Bola() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        hasilluas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        input1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        hasilVolume = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Bola");
        setPreferredSize(new java.awt.Dimension(410, 320));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Hitung");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 36, -1, -1));

        hasilluas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilluasActionPerformed(evt);
            }
        });
        getContentPane().add(hasilluas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 146, 86, -1));

        jLabel1.setText("Luas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 124, -1, -1));

        input1.setText("Masukkan Nilai!");
        input1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input1FocusLost(evt);
            }
        });
        input1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                input1InputMethodTextChanged(evt);
            }
        });
        input1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input1ActionPerformed(evt);
            }
        });
        getContentPane().add(input1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 36, -1, -1));

        jLabel2.setText("Jari");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 39, -1, -1));

        hasilVolume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilVolumeActionPerformed(evt);
            }
        });
        getContentPane().add(hasilVolume, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 146, 97, -1));

        jLabel3.setText("Volume");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 124, -1, -1));

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 71, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jari = Double.parseDouble(input1.getText());
        luas = 4 * (Math.PI * jari * jari);
        volume = ( 4 / 3 ) * (Math.PI * jari * jari * jari);
        hasilluas.setText(String.valueOf(luas));
        hasilVolume.setText(String.valueOf(volume));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void hasilluasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilluasActionPerformed

    }//GEN-LAST:event_hasilluasActionPerformed

    private void input1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_input1InputMethodTextChanged

    }//GEN-LAST:event_input1InputMethodTextChanged

    private void input1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input1ActionPerformed

    }//GEN-LAST:event_input1ActionPerformed

    private void hasilVolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilVolumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilVolumeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        hasilVolume.setText("");
        hasilluas.setText("");
        input1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void input1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input1FocusGained
        if (input1.getText().equals("Masukkan Nilai!"))
        {
            input1.setText("");
        }
    }//GEN-LAST:event_input1FocusGained

    private void input1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input1FocusLost
        if (input1.getText().equals(""))
        {
            input1.setText("Masukkan Nilai!");
        }
    }//GEN-LAST:event_input1FocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hasilVolume;
    private javax.swing.JTextField hasilluas;
    private javax.swing.JTextField input1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
