/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tugasakhirpbo;

/**
 *
 * @author Yafi, Alfito, dan Haydar.
 */
public class PersegiPanjang extends javax.swing.JInternalFrame {
double panjang, lebar, luas, keliling;

    public PersegiPanjang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        hasilluas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        input1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        hasilKeliling = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        input2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Persegi Panjang");
        setPreferredSize(new java.awt.Dimension(410, 320));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Hitung");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 36, -1, -1));

        hasilluas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilluasActionPerformed(evt);
            }
        });
        getContentPane().add(hasilluas, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 146, 86, -1));

        jLabel1.setText("Luas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 124, -1, -1));

        input1.setText("Masukkan Nilai!");
        input1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input1FocusLost(evt);
            }
        });
        input1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                input1InputMethodTextChanged(evt);
            }
        });
        input1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input1ActionPerformed(evt);
            }
        });
        getContentPane().add(input1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 36, -1, -1));

        jLabel2.setText("Panjang");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 39, -1, -1));

        hasilKeliling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilKelilingActionPerformed(evt);
            }
        });
        getContentPane().add(hasilKeliling, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 146, 97, -1));

        jLabel3.setText("Keliling");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 124, -1, -1));

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 71, -1, -1));

        input2.setText("Masukkan Nilai!");
        input2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input2FocusLost(evt);
            }
        });
        input2.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                input2InputMethodTextChanged(evt);
            }
        });
        input2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input2ActionPerformed(evt);
            }
        });
        getContentPane().add(input2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 71, -1, -1));

        jLabel4.setText("Lebar");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 74, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        panjang = Double.parseDouble(input1.getText());
        lebar = Double.parseDouble(input2.getText());
        luas = panjang * lebar;
        keliling = 2 * (panjang + lebar);
        hasilluas.setText(String.valueOf(luas));
        hasilKeliling.setText(String.valueOf(keliling));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void hasilluasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilluasActionPerformed

    }//GEN-LAST:event_hasilluasActionPerformed

    private void hasilKelilingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilKelilingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilKelilingActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        hasilKeliling.setText("");
        hasilluas.setText("");
        input1.setText("");
        input2.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void input2InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_input2InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_input2InputMethodTextChanged

    private void input2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input2ActionPerformed

    private void input1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input1ActionPerformed

    }//GEN-LAST:event_input1ActionPerformed

    private void input1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_input1InputMethodTextChanged

    }//GEN-LAST:event_input1InputMethodTextChanged

    private void input1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input1FocusGained
        if (input1.getText().equals("Masukkan Nilai!"))
        {
            input1.setText("");
        }
    }//GEN-LAST:event_input1FocusGained

    private void input1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input1FocusLost
        if (input1.getText().equals(""))
        {
            input1.setText("Masukkan Nilai!");
        }
    }//GEN-LAST:event_input1FocusLost

    private void input2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input2FocusGained
        if (input2.getText().equals("Masukkan Nilai!"))
        {
            input2.setText("");
        }
    }//GEN-LAST:event_input2FocusGained

    private void input2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input2FocusLost
        if (input2.getText().equals(""))
        {
            input2.setText("Masukkan Nilai!");
        }
    }//GEN-LAST:event_input2FocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hasilKeliling;
    private javax.swing.JTextField hasilluas;
    private javax.swing.JTextField input1;
    private javax.swing.JTextField input2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
